issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false

linters-settings:
  govet:
    enable=fieldalignment: true
  revive:
    rules:
    - name: if-return
      disabled: true

linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

run:
  deadline: 5m
