# Setting SHELL to bash allows bash commands to be executed by recipes.
# This is a requirement for 'setup-envtest.sh' in the test target.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
SHELL = /usr/bin/env bash -o pipefail
.SHELLFLAGS = -ec
.DEFAULT_GOAL:=help

GOARCH  := $(shell go env GOARCH)
GOOS    := $(shell go env GOOS)
GOPROXY := $(shell go env GOPROXY)
ifeq ($(GOPROXY),)
GOPROXY := https://proxy.golang.org
endif
export GOPROXY
# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

TEST_FLAGS ?=
GINKGO_FLAGS ?=
GINKGO_NOCOLOR ?= false

# Image URL to use all building/pushing image targets
RELEASE_VERSION	?= main
IMAGE_REGISTRY	?= ghcr.io/octorun
MANAGER_IMAGE	?= $(IMAGE_REGISTRY)/manager
# ENVTEST_K8S_VERSION refers to the version of kubebuilder assets to be downloaded by envtest binary.
ENVTEST_K8S_VERSION = 1.25

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk commands is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-17s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: manifests
manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	$(CONTROLLER_GEN) rbac:roleName=manager-role crd:generateEmbeddedObjectMeta=true webhook paths="./..." output:crd:artifacts:config=config/crd/bases

.PHONY: generate
generate: controller-gen conversion-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
	$(CONVERSION_GEN) \
		--input-dirs=./api/v1alpha1 \
		--build-tag=ignore_autogenerated_conversions \
		--extra-peer-dirs=octorun.github.io/octorun/api/v1alpha1 \
		--output-file-base=zz_generated.conversion \
		--go-header-file=hack/boilerplate.go.txt $(OUTPUT_BASE)

.PHONY: kubeprom
kubeprom: ## Generate minimal kube-prometheus stack manifests. Generated manifests intended only for development purpose.
	GOBIN=$(LOCALBIN) go install github.com/brancz/gojsontoyaml@latest
	GOBIN=$(LOCALBIN) go install github.com/google/go-jsonnet/cmd/jsonnet@latest
	GOBIN=$(LOCALBIN) go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
ifeq (,$(wildcard hack/kube-prometheus/vendor))
	@cd hack/kube-prometheus && $(LOCALBIN)/jb update
endif
	@rm -rf hack/kube-prometheus/manifests && mkdir -p hack/kube-prometheus/manifests/setup
	$(LOCALBIN)/jsonnet -J hack/kube-prometheus/vendor -m hack/kube-prometheus/manifests hack/kube-prometheus/kubeprom.jsonnet | xargs -I{} sh -c 'cat {} | $(LOCALBIN)/gojsontoyaml > {}.yaml' -- {}
	@find hack/kube-prometheus/manifests -type f ! -name '*.yaml' -delete

.PHONY: crdref
crdref: crdref-gen ## Generate CRDs reference documentation.
	$(CRD_REF_DOCS) --templates-dir=hack/crd-ref-docs/template \
	--config=hack/crd-ref-docs/config.yaml \
	--renderer=markdown \
	--source-path=api/v1alpha2 \
	--output-path=docs/reference/api-reference.md

.PHONY: fmt
fmt: ## Run go fmt against code.
	@go fmt ./...

.PHONY: vet
vet: ## Run go vet against code.
	@go vet ./...

.PHONY: test
test: generate fmt vet ## Run unit tests.
	go test -short ./... -coverprofile cover.out $(TEST_FLAGS)

.PHONY: test-integration
test-integration: manifests generate fmt vet envtest ginkgo ## Run integration tests.
	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" ACK_GINKGO_RC=true $(GINKGO) \
	-slowSpecThreshold 30 -noColor=$(GINKGO_NOCOLOR) $(GINKGO_FLAGS) \
	-focus="RunnerReconciler|RunnerSetReconciler|RunnerWebhook|RunnerSetWebhook" \
	./controllers/... ./webhooks/...

##@ Build

.PHONY: manager
manager: generate fmt vet ## Build manager binary.
	CGO_ENABLED=0 GOOS=${GOOS} GOARCH=${GOARCH} go build -o bin/manager main.go

.PHONY: manager-image
manager-image: ## Build manager container image.
	docker build -t ${MANAGER_IMAGE}:$(RELEASE_VERSION) .

##@ Deployment

ifndef ignore-not-found
  ignore-not-found = false
endif

.PHONY: release
release: manager-image
	docker push ${MANAGER_IMAGE}:$(RELEASE_VERSION)
	cd config/release && $(KUSTOMIZE) edit set image ${MANAGER_IMAGE}=${MANAGER_IMAGE}:$(RELEASE_VERSION)

.PHONY: install
install: manifests kustomize ## Install CRDs into the K8s cluster specified in ~/.kube/config.
	$(KUSTOMIZE) build config/crd | kubectl apply -f -

.PHONY: uninstall
uninstall: manifests kustomize ## Uninstall CRDs from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
	$(KUSTOMIZE) build config/crd | kubectl delete --ignore-not-found=$(ignore-not-found) -f -

.PHONY: deploy
deploy: manifests kustomize ## Deploy controller to the K8s cluster specified in ~/.kube/config.
	cd config/manager && $(KUSTOMIZE) edit set image manager=${MANAGER_IMAGE}
	$(KUSTOMIZE) build config/default | kubectl apply -f -

.PHONY: undeploy
undeploy: ## Undeploy controller from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
	$(KUSTOMIZE) build config/default | kubectl delete --ignore-not-found=$(ignore-not-found) -f -

##@ Tools

## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

## Tool Binaries
CONTROLLER_GEN	?= $(LOCALBIN)/controller-gen
CONVERSION_GEN	?= $(LOCALBIN)/conversion-gen
CRD_REF_DOCS	?= $(LOCALBIN)/crd-ref-docs
KUSTOMIZE	?= $(LOCALBIN)/kustomize
GINKGO		?= $(LOCALBIN)/ginkgo
ENVTEST		?= $(LOCALBIN)/setup-envtest

## Tool Versions
KUSTOMIZE_VERSION ?= v4.5.7
CONVERSION_GEN_VERSION	?= v0.22.2
CONTROLLER_GEN_VERSION	?= v0.9.2

.PHONY: controller-gen
controller-gen: ## Download controller-gen locally if necessary.
	test -s $(CONTROLLER_GEN) || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_GEN_VERSION)

.PHONY: conversion-gen
conversion-gen: ## Download conversion-gen locally if necessary.
	test -s $(CONVERSION_GEN) || GOBIN=$(LOCALBIN) go install k8s.io/code-generator/cmd/conversion-gen@$(CONVERSION_GEN_VERSION)

.PHONY: crdref-gen
crdref-gen: ## Download crd-ref-docs generator locally if necessary.
	test -s $(CRD_REF_DOCS) || GOBIN=$(LOCALBIN) go install github.com/elastic/crd-ref-docs@latest

.PHONY: ginkgo
ginkgo: ## Download ginkgo locally if necessary.
	test -s $(GINKGO) || GOBIN=$(LOCALBIN) go install github.com/onsi/ginkgo/ginkgo@latest

.PHONY: kustomize
kustomize: ## Download kustomize locally if necessary.
	test -s $(KUSTOMIZE) || GOBIN=$(LOCALBIN) go install sigs.k8s.io/kustomize/kustomize/v4@$(KUSTOMIZE_VERSION)

.PHONY: envtest
envtest: ## Download envtest-setup locally if necessary.
	test -s $(ENVTEST) || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
