apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: manager
  newName: ghcr.io/octorun/manager
  newTag: main
resources:
- manager.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
secretGenerator:
- envs:
  - secret.env
  name: manager-secret
  type: generic
