resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patches:
  - target:
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
    patch: |
      apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      metadata:
        name: mutating-webhook-configuration
        labels:
          app.kubernetes.io/component: webhook
      webhooks:
      - name: mrunner.octorun.github.io
        clientConfig:
          service:
            name: manager-webhook
      - name: mrunnerset.octorun.github.io
        clientConfig:
          service:
            name: manager-webhook
  - target:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    patch: |
      apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      metadata:
        name: validating-webhook-configuration
        labels:
          app.kubernetes.io/component: webhook
      webhooks:
      - name: vrunner.octorun.github.io
        clientConfig:
          service:
            name: manager-webhook
      - name: vrunnerset.octorun.github.io
        clientConfig:
          service:
            name: manager-webhook

patchesJson6902:
  - target:
      kind: Service
      name: webhook-service
      version: v1
    patch: |
      - op: replace
        path: /metadata/name
        value: manager-webhook
