---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-octorun-github-io-v1alpha1-runner
  failurePolicy: Fail
  name: mrunner.octorun.github.io
  rules:
  - apiGroups:
    - octorun.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runners
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-octorun-github-io-v1alpha1-runnerset
  failurePolicy: Fail
  name: mrunnerset.octorun.github.io
  rules:
  - apiGroups:
    - octorun.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runnersets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-octorun-github-io-v1alpha1-runner
  failurePolicy: Fail
  name: vrunner.octorun.github.io
  rules:
  - apiGroups:
    - octorun.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runners
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-octorun-github-io-v1alpha1-runnerset
  failurePolicy: Fail
  name: vrunnerset.octorun.github.io
  rules:
  - apiGroups:
    - octorun.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runnersets
  sideEffects: None
