
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  labels:
    app.kubernetes.io/component: webhook
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/instance: manager
