
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: manager-metrics
  namespace: system
spec:
  endpoints:
    - path: /metrics
      honorLabels: true
      relabelings:
      - action: labeldrop
        regex: (pod|service|endpoint|namespace)
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: manager
      app.kubernetes.io/name: octorun
      app.kubernetes.io/part-of: octorun
