resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml
- runner_editor_role.yaml
- runner_viewer_role.yaml
- runnerset_editor_role.yaml
- runnerset_viewer_role.yaml
