# permissions for end users to edit runnersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runnerset-editor-role
rules:
- apiGroups:
  - octorun.github.io
  resources:
  - runnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - octorun.github.io
  resources:
  - runnersets/status
  verbs:
  - get
