# permissions for end users to view runnersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runnerset-viewer-role
rules:
- apiGroups:
  - octorun.github.io
  resources:
  - runnersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - octorun.github.io
  resources:
  - runnersets/status
  verbs:
  - get
